src/client.rs, src/rpc/auth.rs, src/rpc/cluster.rs, src/rpc/election.rs, src/rpc/kv.rs, src/rpc/lease.rs, src/rpc/lock.rs, src/rpc/maintenance.rs, src/rpc/watch.rs
In the Tonic ecosystem, the primary way of sharing a client between
multiple contexts is to clone. The client itself is usually a thin
wrapper over a channel, and the channel itself is meant to be cloned to
support sharing.
All the rpc specific clients and the global client now support cloning
for sharing.
=> Support Clone operation on the client

Cargo.toml, src/client.rs, src/lib.rs
Enabling the new feature tls-roots allows connections over HTTPS without any code changes. This only works if the server certificate is issued by one of the standard CAs.
=> Support TLS connection with optional tonic feature `tls` and `tls-roots`

Cargo.toml, examples/lock.rs, examples/maintenance.rs, src/client.rs, src/rpc/election.rs, src/rpc/lease.rs, src/rpc/watch.rs
Opening this as a draft since new version of tonic has not had an official release yet.
Waiting on:
Both seem close to being merged. :)
=> Upgrade to Tokio 1.0

src/rpc/mod.rs
Signed-off-by: Yu Juncen <yu745514916@live.com>
Fixed #26
A simple demo validating the fix:
```rust
use etcd_client::{Error, KeyValue};
#[derive(Debug)]
struct OwnedKv(Vec<u8>, Vec<u8>);
impl From<KeyValue> for OwnedKv {
fn from(mut kv: KeyValue) -> Self {
let key = std::mem::take(&mut kv.0.key);
let value = std::mem::take(&mut kv.0.value);
Self(key, value)
}
}
#[tokio::main]
async fn main() -> Result<(), Error> {
let mut cli = etcd_client::Client::connect(&["127.0.0.1:2379"], None).await?;
let mut result = cli.get("hello", None).await?;
let r = std::mem::take(&mut result.0.kvs);
println!(
"{:?}",
r.into_iter()
.map::<OwnedKv, _>(|kv| OwnedKv::from(unsafe {
std::mem::transmute::<_, KeyValue>(kv)
}))
.collect::<Vec<_>>()
);
Ok(())
}
```
=> Fix: allow KeyValue be exported by feature pub-response-field

src/client.rs
I found `etcd-client` will return err when single endpoint  is temporarily unavailable, but OK and will reconnect for two temporarily unavailable endpoints.
The reason is tonic `Channel::balance_list` internally called  `lazy` [here]( https://github.com/hyperium/tonic/blob/4b0ece6d2854af088fbc1bdb55c2cdd19ec9bb92/tonic/src/transport/service/discover.rs#L45), 
It will be good to connect lazy for single endpoint as well.
=> Connect lazy for single endpoint

README.md, src/lib.rs
rustdoc doesn't identify "\```Rust" but "```rust" exactly.
.. also in README.md. Although GitHub can properly render "```Rust", keep it consistent.
Signed-off-by: tison <wander4096@gmail.com>
Current:
After:
=> fix highlight for rustdoc

src/client.rs
Signed-off-by: TennyZhuang <zty0826@gmail.com>
The timeout for each request is important in many scenarios.
=> Add timeout to ConnectOptions

Cargo.toml, src/client.rs, src/error.rs
Hey, David
In this PR, I expose the inner `Sender` to support endpoint dynamic changes, for applications, without breaking changes.
- `connect_with_balance` the same as the original `connect` except in balance only and saving the `tx` inside the `Client` struct
- `build_endpoints`helper for applications to build `Endpoint`s from str and options
- `is_dynamic`
- `add_endpoint`
- `remove_endpoint`
Maybe in `connect` function, we should save the `tx` if there are more than one endpoint.
In addition, it's better to use `Channel::balance_channel` instead of `Channel::balance_list` which drops the inner `tx`. And `tonic` [may be removed it in the future](https://github.com/hyperium/tonic/pull/939#issuecomment-1069326905).
=> Dynamically add/remove endpoint

Cargo.toml, README.md
Changelog: https://github.com/hyperium/tonic/blob/master/CHANGELOG.md#v090-2023-03-31
Note that this will bump MSRV to 1.60.
=> Upgrade tonic to 0.9.x and other dependencies

Cargo.toml
Turns out `tonic-build` 0.9 generates code that only compiles with 2021 edition.
See also https://github.com/hyperium/tonic/issues/1345
=> Upgrade to Rust 2021 edition

src/rpc/kv.rs, src/rpc/watch.rs
Currently its not possible to define tonic options to change `max_encoding_message_size` and `max_decoding_message_size`
I redefined them in `KvClient` and `WatchClient` (I didn't add `max_encoding_message_size` for watch client as I don't see any use case for it)
```rust
let etcd_client = etcd_client::Client::connect(["localhost:2379"], None).await.unwrap();
let etcd_kv_client = etcd_client
.kv_client()
.max_encoding_message_size(10* 1024 * 1024);
.max_decoding_message_size(10* 1024 * 1024);
let etcd_watch_client = etcd_client
.watch_client()
.max_decoding_message_size(10* 1024 * 1024);
```
=> tonic options max_decoding_message_size/max_encoding_message_size

src/rpc/kv.rs
Just like `take_prev_key` for `PutResponse`.
I found this helper function help when HACKING https://github.com/GreptimeTeam/greptimedb/pull/2734.
=> Implement take_prev_kvs for DeleteResponse

src/rpc/kv.rs, src/rpc/mod.rs
cc @davidli2010 I just noticed that `GetResponse#take_kvs` are ignored in my previous PR - it's needed to avoid copy kvs also.
=> Add GetResponse::take_kvs() & KeyValue::into_key_value()

src/rpc/kv.rs
Data layout of `Vec` is unspecified. Transmuting vectors can cause Undefined Behavior even when items are transparent types:
<https://doc.rust-lang.org/std/mem/fn.transmute.html#alternatives>
This PR replaced transmuting on vectors with the recommended way mentioned in link above.
=> Safely transmute vectors

Cargo.toml
This raises the MSRV to 1.70, so probably warrants a minor release, though I don't think `etcd-client` actually specifies an MSRV.
=> Update tonic to 0.11

.github/workflows/ci.yml, Cargo.toml, src/openssl_tls/transport.rs
=> build(deps): upgrade for hyper 1.x 

examples/maintenance.rs
The proposed changes make things clearer about the snapshot hash information.
* Snapshot hash is sent after the first occurance of `r.remaining_bytes() == 0`. See https://github.com/etcd-io/etcd/pull/11896 for more information.
* If the snapshot operation is performed as shown in the example previously, restarting the etcd on the stored data from this won't succeed unless etcd is started with `--skip-hash-check=true`. This isn't necessary anymore since the final `msg.message().await` fetches the snapshot hash information.
etcd used: 
```
etcd Version: 3.5.11
Git SHA: 3b252db4f
Go Version: go1.21.5
Go OS/Arch: darwin/arm64
```
etcd-client: `v0.14.0`
=> Enhance the example which showcases the snapshot maintenance operation.

Cargo.toml, build.rs, examples/lease.rs, src/rpc/lease.rs, tests/client.rs
Currently [lease_keep_alive](https://github.com/etcdv3/etcd-client/blob/f9110dfc7c6bb2e289535fb717e536a143a6dac0/src/client.rs#L431-L439) returns lease keeper and keep alive stream even when the lease id is not found or revoked, in such case `LeaseKeeper.keep_alive` will not return error and the keep alive stream will yield nothing, so we can't identify that the lease id is invalid.
This patch changes `lease_keep_alive` to return an error when the `lease_id` argument passed has `ttl <= 0` (which means it's expired or revoked, in other words `not found`).
See also https://github.com/etcd-io/etcd/blob/b4450d510ddf0f011c874c28e95175b4bac7f6c8/client/v3/lease.go#L323-L325
=> lease keep alive return lease not found error

README.md
As the MSRV was recently updated, this patch makes the badge display the current MSRV correctly.
=> fix: change MSRV badge to 1.80

src/openssl_tls/transport.rs
When attempting to run `cargo test -F tls-openssl` on my local machine, the `openssl_tls::transport` doctests attempted to compile, but failed. The `no_run` directive specified in the tests prevents them from being run, but does not prevent them from compiling, so this patch fixes their compilation to enable local development via
`cargo test -F tls-openssl`.
=> fix: make doctests in openssl_tls::transport compile

src/client.rs, src/intercept.rs, src/lib.rs, src/rpc/auth.rs, src/rpc/cluster.rs, src/rpc/election.rs, src/rpc/kv.rs, src/rpc/lease.rs, src/rpc/lock.rs, src/rpc/maintenance.rs, src/rpc/watch.rs, tests/testing.rs
Some etcd functions require a leader to be present in the partition that the client is connected to. As per Raft, it is useful for a client to be able to guarantee the presence of a leader on each request, as this is a method for detecting if the client is connected to the majority partition.
As per the Golang implementation of the etcdv3 client, this functionality is exposed through the use of gRPC custom metadata, which is supported in Tonic through the Interceptors system. This patch adds a connection option that allows the client to enforce the presence of a leader, and implements it through the use of an interceptor that attaches the metadata parameter to the gRPC client.
=> feat: add support for requiring a leader

.github/workflows/ci.yml, src/client.rs
Currently, in the GitHub Actions CI, only the default features are actually run through `cargo clippy`. This patch adds support for testing all _combinations_ of features via `cargo-hack`, excluding the mutually-exclusive `tls` and `tls-openssl` features.
This change is not intended to be a comprehensive validation of all combinations of features, but instead a check to verify all code actually compiles with all combinations of features. It can, however, be extended to support running tests with all combinations. That will be rather complex, given the need to create a TLS cert chain to comprehensively test TLS support, so that task was not done here.
This CI change caught a case where the existing code produces a warning when compiling with `tls-openssl` enabled. This patch also fixes …
=> feat(ci): run cargo clippy with all feature combinations

Cargo.toml, build.rs, src/lib.rs
In order to support Determinstic Simulation Testing (DST) via the `turmoil` crate, this patch introduces a new feature flag, `build-server`, which builds a server variant of the etcd protobuf and re-exports it under the same `proto` package as the `pub-response-field` feature flag does. This enables a downstream user to implement various mock etcd scenarios within a Turmoil environment, allowing for more precise testing.
=> feat: add the ability to build a server

Cargo.toml, README.md, src/client.rs, src/error.rs, src/lib.rs
In some scenarios, such as when using a Deterministic Simulation Testing environment such as `turmoil`, when mocking the behaviour of etcd itself, or using non-Tokio sockets for connecting to etcd, it is desirable to construct a Tonic channel externally, then "wrap" it in a `Client` object. This patch enables this use case by creating a `RawClient` type, which is constructed from an existing Tonic channel.
In order to ensure maximum code re-use, the existing `Client` is updated to use the `RawClient` type internally.
=> feat: allow caller to initialize the channel

clippy.toml
> ```
>  error: the `Err`-variant returned from this function is very large
>     --> src/client.rs:156:71
>      |
>  156 |     fn build_endpoint(url: &str, options: &Option<ConnectOptions>) -> Result<Endpoint> {
>      |                                                                       ^^^^^^^^^^^^^^^^
>      |
>     ::: src/error.rs:24:5
>      |
>  24  |     GRpcStatus(tonic::Status),
>      |     ------------------------- the largest variant contains at least 176 bytes
>      |
>      = help: try reducing the size of `error::Error`, for example by boxing large elements or replacing it with `Box<error::Error>`
>      = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#result_large_err
>      = note: `-D clippy::result-large-err` implied …
```
=> Set large-error-threshold to 256 for rust 1.87

Cargo.toml, build.rs, examples/auth_role.rs, examples/auth_user.rs, examples/cluster.rs, examples/kv.rs, examples/lease.rs, examples/lock.rs, examples/maintenance.rs, src/channel.rs, src/client.rs, src/error.rs, src/openssl_tls/backoff.rs, src/openssl_tls/transport.rs, src/rpc/watch.rs
The tonic `0.13` release is a breaking release, including many deps and also feature flags. But this release is planned to be a long term release.
- `tonic`: `0.12.3` -> `0.13.1`
- `tonic-build`: `0.12.3` -> `0.13.1`
- `tower`: `0.4` -> `0.5`
- https://github.com/hyperium/tonic/releases/tag/v0.13.0
=> Upgrade tonic to 0.13.1 and tower to 0.5

src/channel.rs
Use `BoxCloneSyncService` instead of `BoxCloneService` for `CustomChannel` to keep Client Sync.
See #109
Introduced in #98
=> Fix `Client` (`Channel`) `Sync`
